name: Release Charts

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: |
          helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          helm repo add ncsa https://opensource.ncsa.illinois.edu/charts/
          helm dep build

      - name: get release info
        id: release_info
        run: |
          version="$(awk '/^version:/ { print $2} ' Chart.yaml)"
          changelog="$(sed -e "1,/^### ${version}/d" -e "/^###/,\$d" -e '/^$/d' README.md)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "changelog=$changelog" >> $GITHUB_OUTPUT

      - name: Publish to NCSA OpenSource
        uses: bsord/helm-push@v4.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.HELM_USERNAME }}
          password: ${{ secrets.HELM_PASSWORD }}
          registry-url: "https://opensource.ncsa.illinois.edu/charts"
          chart-folder: "."
          force: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clowder-${{ steps.release_info.outputs.version }}.tgz
          body: ${{ steps.release_info.outputs.changelog }}
